var countryCodeLookup = 
{
	"Afghanistan": "AFG",
	"Åland Islands": "ALA",
	"Albania": "ALB",
	"Algeria": "DZA",
	"American Samoa": "ASM",
	"Andorra": "AND",
	"Angola": "AGO",
	"Anguilla": "AIA",
	"Antigua and Barbuda": "ATG",
	"Argentina": "ARG",
	"Armenia": "ARM",
	"Aruba": "ABW",
	"Australia": "AUS",
	"Austria": "AUT",
	"Azerbaijan": "AZE",
	"Bahamas": "BHS",
	"Bahrain": "BHR",
	"Bangladesh": "BGD",
	"Barbados": "BRB",
	"Belarus": "BLR",
	"Belgium": "BEL",
	"Belize": "BLZ",
	"Benin": "BEN",
	"Bermuda": "BMU",
	"Bhutan": "BTN",
	"Bolivia (Plurinational State of)": "BOL",
	"Bonaire, Sint Eustatius and Saba": "BES",
	"Bosnia and Herzegovina": "BIH",
	"Botswana": "BWA",
	"Brazil": "BRA",
	"British Virgin Islands": "VGB",
	"Brunei Darussalam": "BRN",
	"Bulgaria": "BGR",
	"Burkina Faso": "BFA",
	"Burundi": "BDI",
	"Cabo Verde": "CPV",
	"Cambodia": "KHM",
	"Cameroon": "CMR",
	"Canada": "CAN",
	"Cayman Islands": "CYM",
	"Central African Republic": "CAF",
	"Chad": "TCD",
	"Channel Islands": "",
	"Chile": "CHL",
	"China": "CHN",
	"China, Hong Kong Special Administrative Region": "HKG",
	"China, Macao Special Administrative Region": "MAC",
	"Colombia": "COL",
	"Comoros": "COM",
	"Congo": "COG",
	"Cook Islands": "COK",
	"Costa Rica": "CRI",
	"Côte d'Ivoire": "CIV",
	"Croatia": "HRV",
	"Cuba": "CUB",
	"Curaçao": "CUW",
	"Cyprus": "CYP",
	"Czech Republic": "CZE",
	"Democratic People's Republic of Korea": "PRK",
	"Democratic Republic of the Congo": "COD",
	"Denmark": "DNK",
	"Djibouti": "DJI",
	"Dominica": "DMA",
	"Dominican Republic": "DOM",
	"Ecuador": "ECU",
	"Egypt": "EGY",
	"El Salvador": "SLV",
	"Equatorial Guinea": "GNQ",
	"Eritrea": "ERI",
	"Estonia": "EST",
	"Ethiopia": "ETH",
	"Faeroe Islands": "FRO",
	"Falkland Islands (Malvinas)": "FLK",
	"Fiji": "FJI",
	"Finland": "FIN",
	"France": "FRA",
	"French Guiana": "GUF",
	"French Polynesia": "PYF",
	"Gabon": "GAB",
	"Gambia": "GMB",
	"Georgia": "GEO",
	"Germany": "DEU",
	"Ghana": "GHA",
	"Gibraltar": "GIB",
	"Greece": "GRC",
	"Greenland": "GRL",
	"Grenada": "GRD",
	"Guadeloupe": "GLP",
	"Guam": "GUM",
	"Guatemala": "GTM",
	"Guernsey": "GGY",
	"Guinea": "GIN",
	"Guinea-Bissau": "GNB",
	"Guyana": "GUY",
	"Haiti": "HTI",
	"Holy See": "VAT",
	"Honduras": "HND",
	"Hungary": "HUN",
	"Iceland": "ISL",
	"India": "IND",
	"Indonesia": "IDN",
	"Iran (Islamic Republic of)": "IRN",
	"Iraq": "IRQ",
	"Republic of Ireland": "IRL",
	"Isle of Man": "IMN",
	"Israel": "ISR",
	"Italy": "ITA",
	"Jamaica": "JAM",
	"Japan": "JPN",
	"Jersey": "JEY",
	"Jordan": "JOR",
	"Kazakhstan": "KAZ",
	"Kenya": "KEN",
	"Kiribati": "KIR",
	"Kuwait": "KWT",
	"Kyrgyzstan": "KGZ",
	"Lao People's Democratic Republic": "LAO",
	"Latvia": "LVA",
	"Lebanon": "LBN",
	"Lesotho": "LSO",
	"Liberia": "LBR",
	"Libya": "LBY",
	"Liechtenstein": "LIE",
	"Lithuania": "LTU",
	"Luxembourg": "LUX",
	"Madagascar": "MDG",
	"Malawi": "MWI",
	"Malaysia": "MYS",
	"Maldives": "MDV",
	"Mali": "MLI",
	"Malta": "MLT",
	"Marshall Islands": "MHL",
	"Martinique": "MTQ",
	"Mauritania": "MRT",
	"Mauritius": "MUS",
	"Mayotte": "MYT",
	"Mexico": "MEX",
	"Micronesia (Federated States of)": "FSM",
	"Monaco": "MCO",
	"Mongolia": "MNG",
	"Montenegro": "MNE",
	"Montserrat": "MSR",
	"Morocco": "MAR",
	"Mozambique": "MOZ",
	"Myanmar": "MMR",
	"Namibia": "NAM",
	"Nauru": "NRU",
	"Nepal": "NPL",
	"Netherlands": "NLD",
	"New Caledonia": "NCL",
	"New Zealand": "NZL",
	"Nicaragua": "NIC",
	"Niger": "NER",
	"Nigeria": "NGA",
	"Niue": "NIU",
	"Norfolk Island": "NFK",
	"Northern Mariana Islands": "MNP",
	"Norway": "NOR",
	"Oman": "OMN",
	"Pakistan": "PAK",
	"Palau": "PLW",
	"Panama": "PAN",
	"Papua New Guinea": "PNG",
	"Paraguay": "PRY",
	"Peru": "PER",
	"Philippines": "PHL",
	"Pitcairn": "PCN",
	"Poland": "POL",
	"Portugal": "PRT",
	"Puerto Rico": "PRI",
	"Qatar": "QAT",
	"Republic of Korea": "KOR",
	"Republic of Moldova": "MDA",
	"Réunion": "REU",
	"Romania": "ROU",
	"Russian Federation": "RUS",
	"Rwanda": "RWA",
	"Saint Barthélemy": "BLM",
	"Saint Helena": "SHN",
	"Saint Kitts and Nevis": "KNA",
	"Saint Lucia": "LCA",
	"Saint Martin (French part)": "MAF",
	"Saint Pierre and Miquelon": "SPM",
	"Saint Vincent and the Grenadines": "VCT",
	"Samoa": "WSM",
	"San Marino": "SMR",
	"Sao Tome and Principe": "STP",
	"Sark": " ",
	"Saudi Arabia": "SAU",
	"Senegal": "SEN",
	"Serbia": "SRB",
	"Seychelles": "SYC",
	"Sierra Leone": "SLE",
	"Singapore": "SGP",
	"Sint Maarten (Dutch part)": "SXM",
	"Slovakia": "SVK",
	"Slovenia": "SVN",
	"Solomon Islands": "SLB",
	"Somalia": "SOM",
	"South Africa": "ZAF",
	"South Sudan": "SSD",
	"Spain": "ESP",
	"Sri Lanka": "LKA",
	"State of Palestine": "PSE",
	"Sudan": "SDN",
	"Suriname": "SUR",
	"Svalbard and Jan Mayen Islands": "SJM",
	"Swaziland": "SWZ",
	"Sweden": "SWE",
	"Switzerland": "CHE",
	"Syrian Arab Republic": "SYR",
	"Taiwan": "TWN",
	"Tajikistan": "TJK",
	"Thailand": "THA",
	"The former Yugoslav Republic of Macedonia": "MKD",
	"Timor-Leste": "TLS",
	"Togo": "TGO",
	"Tokelau": "TKL",
	"Tonga": "TON",
	"Trinidad and Tobago": "TTO",
	"Tunisia": "TUN",
	"Turkey": "TUR",
	"Turkmenistan": "TKM",
	"Turks and Caicos Islands": "TCA",
	"Tuvalu": "TUV",
	"Uganda": "UGA",
	"Ukraine": "UKR",
	"United Arab Emirates": "ARE",
	"United Kingdom": "GBR",
	"United Republic of Tanzania": "TZA",
	"United States": "USA",
	"United States Virgin Islands": "VIR",
	"Uruguay": "URY",
	"Uzbekistan": "UZB",
	"Vanuatu": "VUT",
	"Venezuela (Bolivarian Republic of)": "VEN",
	"Viet Nam": "VNM",
	"Wallis and Futuna Islands": "WLF",
	"Western Sahara": "ESH",
	"Yemen": "YEM",
	"Zambia": "ZMB",
	"Zimbabwe": "ZWE"
}